local mod = "__DeadlockStackingForExoticIndustries__/graphics/icons/"

local Items = {}

Items.items = {
    -- Dark Age
    ["ei_poor-iron-chunk"] = { icon = mod .. "stacked-poor-iron-chunk.png", icon_size = 64 },
    ["ei_poor-copper-chunk"] = { icon = mod .. "stacked-poor-copper-chunk.png", icon_size = 64 },
    ["ei_slag"] = { icon = mod .. "stacked-slag.png", icon_size = 64, tech = "DEFAULT" },
    ["ei_iron-ingot"] = { icon = mod .. "stacked-iron-ingot.png", icon_size = 64, tech = "DEFAULT" },
    ["ei_copper-ingot"] = { icon = mod .. "stacked-copper-ingot.png", icon_size = 64, tech = "DEFAULT" },
    ["ei_iron-beam"] = { icon = mod .. "stacked-iron-beam.png", icon_size = 64 },
    ["ei_copper-beam"] = { icon = mod .. "stacked-copper-beam.png", icon_size = 64 },
    ["ei_iron-mechanical-parts"] = { icon = mod .. "stacked-iron-mechanical-parts.png", icon_size = 64 },
    ["ei_copper-mechanical-parts"] = { icon = mod .. "stacked-copper-mechanical-parts.png", icon_size = 64 },
    ["ei_steam-engine"] = { icon = mod .. "stacked-steam-engine.png", icon_size = 64 },
    -- Steam Age
    ["ei_coke"] = { icon = mod .. "stacked-coke.png", icon_size = 64 },
    ["ei_coke-pellets"] = { icon = mod .. "stacked-coke-pellets.png", icon_size = 64 },
    ["ei_crushed-coke"] = { icon = mod .. "stacked-crushed-coke.png", icon_size = 64 },
    ["ei_charcoal"] = { icon = mod .. "stacked-charcoal.png", icon_size = 64 },
    ["ei_crushed-iron"] = { icon = mod .. "stacked-crushed-iron.png", icon_size = 64 },
    ["ei_steel-blend"] = { icon = mod .. "stacked-steel-blend.png", icon_size = 64 },
    ["ei_steel-ingot"] = { icon = mod .. "stacked-steel-ingot.png", icon_size = 64 },
    ["ei_steel-beam"] = { icon = mod .. "stacked-steel-plate.png", icon_size = 64 },
    ["ei_steel-mechanical-parts"] = { icon = mod .. "stacked-steel-mechanical-parts.png", icon_size = 64 },
    ["ei_sand"] = { icon = mod .. "stacked-sand.png", icon_size = 64 },
    ["ei_ceramic"] = { icon = mod .. "stacked-ceramic.png", icon_size = 64 },
    ["ei_electron-tube"] = { icon = mod .. "stacked-electron-tube.png", icon_size = 64 },
    ["ei_glass"] = { icon = mod .. "stacked-glass.png", icon_size = 64 },
    -- Electricity Age
    ["ei_insulated-wire"] = { icon = mod .. "stacked-insulated-wire.png", icon_size = 64 },
    ["ei_crushed-copper"] = { icon = mod .. "stacked-crushed-copper.png", icon_size = 64 },
    ["ei_fluorite"] = { icon = mod .. "stacked-fluorite.png", icon_size = 64 },
    ["ei_cpu"] = { icon = mod .. "stacked-cpu.png", icon_size = 64 },
    ["ei_electronic-parts"] = { icon = mod .. "stacked-electronic-parts.png", icon_size = 64 },
    ["ei_crushed-gold"] = { icon = mod .. "stacked-crushed-gold.png", icon_size = 64 },
    ["ei_gold-ingot"] = { icon = mod .. "stacked-gold-ingot.png", icon_size = 64 },
    ["ei_gold-plate"] = { icon = mod .. "stacked-gold-plate.png", icon_size = 64 },
    ["ei_neodym-ingot"] = { icon = mod .. "stacked-neodym-ingot.png", icon_size = 64 },
    ["ei_neodym-plate"] = { icon = mod .. "stacked-neodym-plate.png", icon_size = 64 },
    ["ei_lead-ingot"] = { icon = mod .. "stacked-lead-ingot.png", icon_size = 64 },
    ["ei_lead-plate"] = { icon = mod .. "stacked-lead-plate.png", icon_size = 64 },
    ["ei_gold-chunk"] = { icon = mod .. "stacked-gold-chunk.png", icon_size = 64 },
    ["ei_lead-chunk"] = { icon = mod .. "stacked-lead-chunk.png", icon_size = 64 },
    ["ei_neodym-chunk"] = { icon = mod .. "stacked-neodym-chunk.png", icon_size = 64 },
    ["ei_coal-chunk"] = { icon = mod .. "stacked-coal-chunk.png", icon_size = 64 },
    ["ei_iron-chunk"] = { icon = mod .. "stacked-iron-chunk.png", icon_size = 64 },
    ["ei_copper-chunk"] = { icon = mod .. "stacked-copper-chunk.png", icon_size = 64 },
    ["ei_uranium-chunk"] = { icon = mod .. "stacked-uranium-chunk.png", icon_size = 64 },
    ["ei_faulty-semiconductor"] = { icon = mod .. "stacked-faulty-waver.png", icon_size = 64 },
    ["ei_semiconductor"] = { icon = mod .. "stacked-waver.png", icon_size = 64 },
    ["ei_crushed-uranium"] = { icon = mod .. "stacked-crushed-uranium.png", icon_size = 64 },
    ["ei_crushed-pure-uranium"] = { icon = mod .. "stacked-crushed-pure-uranium.png", icon_size = 64 },
    ["ei_nuclear-waste"] = { icon = mod .. "stacked-nuclear-waste.png", icon_size = 64 },
    ["ei_uranium-test-fuel"] = { icon = mod .. "stacked-test-fuel.png", icon_size = 64 },
    ["ei_uranium-235-fuel"] = { icon = mod .. "stacked-uranium-235-fuel.png", icon_size = 64 },
    ["ei_used-uranium-235-fuel"] = { icon = mod .. "stacked-used-uranium-235-fuel.png", icon_size = 64 },
    ["ei_energy-crystal"] = { icon = mod .. "stacked-energy-crystal.png", icon_size = 64 },
    ["ei_pure-iron"] = { icon = mod .. "stacked-iron-ore.png", icon_size = 64 },
    ["ei_pure-copper"] = { icon = mod .. "stacked-copper-ore.png", icon_size = 64 },
    ["ei_pure-lead"] = { icon = mod .. "stacked-pure-lead.png", icon_size = 64 },
    ["ei_pure-gold"] = { icon = mod .. "stacked-pure-gold.png", icon_size = 64 },
    -- Computer Age
    ["ei_module-part"] = { icon = mod .. "stacked-module-part.png", icon_size = 64 },
    ["ei_module-base"] = { icon = mod .. "stacked-module-base.png", icon_size = 64 },
    ["ei_high-energy-crystal"] = { icon = mod .. "stacked-high-energy-crystal.png", icon_size = 64 },
    ["ei_advanced-motor"] = { icon = mod .. "stacked-advanced-motor.png", icon_size = 64 },
    ["ei_rocket-parts"] = { icon = mod .. "stacked-rocket-parts.png", icon_size = 64 },
    ["ei_advanced-semiconductor"] = { icon = mod .. "stacked-advanced-waver.png", icon_size = 64 },
    ["ei_advanced-base-semiconductor"] = { icon = mod .. "stacked-advanced-base-waver.png", icon_size = 64 },
    ["ei_computing-unit"] = { icon = mod .. "stacked-computing-unit.png", icon_size = 64 },
    ["ei_uranium-233-fuel"] = { icon = mod .. "stacked-uranium-233-fuel.png", icon_size = 64 },
    ["ei_used-uranium-233-fuel"] = { icon = mod .. "stacked-used-uranium-233-fuel.png", icon_size = 64 },
    ["ei_plutonium-239-fuel"] = { icon = mod .. "stacked-plutonium-239-fuel.png", icon_size = 64 },
    ["ei_used-plutonium-239-fuel"] = { icon = mod .. "stacked-used-plutonium-239-fuel.png", icon_size = 64 },
    ["ei_used-thorium-232-fuel"] = { icon = mod .. "stacked-used-thorium-232-fuel.png", icon_size = 64 },
    ["ei_plutonium-239"] = { icon = mod .. "stacked-plutonium-239.png", icon_size = 64 },
    ["ei_uranium-233"] = { icon = mod .. "stacked-uranium-233.png", icon_size = 64 },
    ["ei_thorium-232"] = { icon = mod .. "stacked-thorium-232.png", icon_size = 64 },
    ["ei_fission-data"] = { icon = mod .. "stacked-fission-data.png", icon_size = 64 },
    ["ei_simulation-data"] = { icon = mod .. "stacked-simulation-data.png", icon_size = 64 },
    -- Quantum Age
    ["ei_plasma-data"] = { icon = mod .. "stacked-plasma-data.png", icon_size = 64 },
    ["ei_photon-cavity"] = { icon = mod .. "stacked-photon-cavity.png", icon_size = 64 },
    ["ei_gluon-cavity"] = { icon = mod .. "stacked-gluon-cavity.png", icon_size = 64 },
    ["ei_z-boson-cavity"] = { icon = mod .. "stacked-z-boson-cavity.png", icon_size = 64 },
    ["ei_crushed-neodym"] = { icon = mod .. "stacked-crushed-neodym.png", icon_size = 64 },
    ["ei_pure-crushed-neodym"] = { icon = mod .. "stacked-crushed-pure-neodym.png", icon_size = 64 },
    ["ei_crushed-coal"] = { icon = mod .. "stacked-crushed-coal.png", icon_size = 64 },
    ["ei_carbon"] = { icon = mod .. "stacked-carbon.png", icon_size = 64 },
    ["ei_carbon-nanotube"] = { icon = mod .. "stacked-carbon-nanotube.png", icon_size = 64 },
    ["ei_carbon-structure"] = { icon = mod .. "stacked-carbon-structure.png", icon_size = 64 },
    ["ei_magnet"] = { icon = mod .. "stacked-magnet.png", icon_size = 64 },
    ["ei_magnet-data"] = { icon = mod .. "stacked-magnet-data.png", icon_size = 64 },
    ["ei_fusion-data"] = { icon = mod .. "stacked-fusion-data.png", icon_size = 64 },
    ["ei_sun-data"] = { icon = mod .. "stacked-sun-data.png", icon_size = 64 },
    ["ei_gas-giant-data"] = { icon = mod .. "stacked-gas-giant-data.png", icon_size = 64 },
    ["ei_odd-plating"] = { icon = mod .. "stacked-odd-plating.png", icon_size = 64 },
    ["ei_plasma-cube"] = { icon = mod .. "stacked-plasma-cube.png", icon_size = 64 },
    ["ei_eu-circuit"] = { icon = mod .. "stacked-eu-circuit.png", icon_size = 64 },
    ["ei_eu-magnet"] = { icon = mod .. "stacked-eu-magnet.png", icon_size = 64 },
    ["ei_exotic-matter-up"] = { icon = mod .. "stacked-exotic-matter-up.png", icon_size = 64 },
    ["ei_exotic-matter-down"] = { icon = mod .. "stacked-exotic-matter-down.png", icon_size = 64 },
    ["ei_high-tech-parts"] = { icon = mod .. "stacked-exotic-matter-down.png", icon_size = 64 },
    ["ei_advanced-rocket-fuel"] = { icon = mod .. "stacked-advanced-rocket-fuel.png", icon_size = 64 },
    ["ei_lithium-crystal"] = { icon = mod .. "stacked-lithium-crystal.png", icon_size = 64 },
    ["ei_superior-data"] = { icon = mod .. "stacked-superior-data.png", icon_size = 64 },
    -- Exotic Age
    ["ei_black-hole-data"] = { icon = mod .. "stacked-black-hole-data.png", icon_size = 64 },
    --
}

return Items
